// GENERATED by tools/gen_provenance.py - do not edit by hand.
//
// WHAT FILLS EACH TABLE. sqlOwner.ts says which SQL file CREATES a relation,
// which is what a missing-relation error needs. This says which job PUTS ROWS
// IN IT - so an empty panel can say "the Databank action fills this, it runs
// daily, and it has never run" instead of showing nothing and leaving the
// reader to guess whether that is a bug, a job that never ran, or a quiet day.
export type Filler = {
  /** action = GitHub Actions, n8n = an imported workflow */
  kind: "action" | "n8n";
  /** what it is called where you would go to run it */
  name: string;
  /** the file, so it can be found without knowing the name */
  file: string;
  /** in words, not cron */
  cadence: string;
  /** the script or step that does the writing */
  how: string;
};

export const FILLED_BY: Record<string, Filler[]> = {
  "anomalies": [
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/edge_engine.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "backtest_results": [
    {
      "cadence": "only when you run it",
      "file": "backtest.yml",
      "how": "scripts/backtest/runner.py",
      "kind": "action",
      "name": "Backtest"
    },
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/backtest/runner.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "backtest_trades": [
    {
      "cadence": "only when you run it",
      "file": "backtest.yml",
      "how": "scripts/backtest/runner.py",
      "kind": "action",
      "name": "Backtest"
    },
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/backtest/runner.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "band_probabilities": [
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/probability_engine.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "bands": [
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P0.2_market_discovery.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P0.2 - Market Discovery"
    }
  ],
  "book_snapshots": [
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P0.3_book_volume_snapshot.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P0.3 - Book + Volume Snapshot"
    }
  ],
  "cities": [
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P1.2_nws_monitor.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P1.2 - NWS Monitor"
    },
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P1.3_nws_forecast.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P1.3 - NWS Forecast"
    }
  ],
  "derived_band_day_volume": [
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P0.4_trade_history.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P0.4 - Trade History"
    }
  ],
  "derived_calibration_adjustment": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/capacity.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "derived_capacity": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/capacity.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "derived_city_climate": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/capacity.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "derived_city_correlation": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/capacity.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "derived_city_day_features": [
    {
      "cadence": "daily",
      "file": "archive_observations.yml",
      "how": "scripts/archive_observations.py",
      "kind": "action",
      "name": "Archive Observations"
    },
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/capacity.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "derived_city_day_volume": [
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P0.4_trade_history.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P0.4 - Trade History"
    }
  ],
  "derived_climb_profile": [
    {
      "cadence": "daily",
      "file": "archive_observations.yml",
      "how": "scripts/archive_observations.py",
      "kind": "action",
      "name": "Archive Observations"
    },
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/capacity.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "derived_forecast_skill": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/measure_skill.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "derived_forecast_skill_model": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/measure_skill.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "derived_model_forecast": [
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/weather_model.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    },
    {
      "cadence": "weekly",
      "file": "weather_model.yml",
      "how": "scripts/weather_model.py",
      "kind": "action",
      "name": "Weather Model"
    }
  ],
  "derived_model_promotion": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/model_promotion.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "derived_weather_model": [
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/weather_model.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    },
    {
      "cadence": "weekly",
      "file": "weather_model.yml",
      "how": "scripts/weather_model.py",
      "kind": "action",
      "name": "Weather Model"
    }
  ],
  "derived_weather_peak": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/capacity.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "edges": [
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/edge_engine.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "fact_band_outcome": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/databank.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "fact_forecast_outcome": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/databank.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "fact_signal_outcome": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/databank.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "ledger": [
    {
      "cadence": "only when you run it",
      "file": "verify_resolution_source.yml",
      "how": "scripts/settlement.py",
      "kind": "action",
      "name": "Verify Resolution Source"
    }
  ],
  "live_weather": [
    {
      "cadence": "only when you run it",
      "file": "live_weather.yml",
      "how": "scripts/live_weather.py",
      "kind": "action",
      "name": "Live Weather Monitor"
    },
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P1.2_nws_monitor.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P1.2 - NWS Monitor"
    },
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P1.5_open_meteo.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P1.5 - Open-Meteo Global"
    }
  ],
  "markets": [
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P0.2_market_discovery.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P0.2 - Market Discovery"
    },
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P0.5_refresh_rules_text.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P0.5 - Refresh Rules Text"
    }
  ],
  "paper_activity": [
    {
      "cadence": "only when you run it",
      "file": "paper_fill.yml",
      "how": "scripts/paper_worker.py",
      "kind": "action",
      "name": "Fill Queued Paper Orders"
    },
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/paper_settlement.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    },
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/paper_exits.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    },
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P2.2_paper_maintenance.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P2.2 - Paper Maintenance"
    }
  ],
  "paper_book_evidence": [
    {
      "cadence": "only when you run it",
      "file": "paper_fill.yml",
      "how": "scripts/paper_worker.py",
      "kind": "action",
      "name": "Fill Queued Paper Orders"
    },
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/paper_worker.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "paper_orders": [
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/paper_exits.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "paper_position_settlements": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/paper_settlement.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    },
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/paper_settlement.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "paper_positions": [
    {
      "cadence": "only when you run it",
      "file": "paper_fill.yml",
      "how": "scripts/paper_worker.py",
      "kind": "action",
      "name": "Fill Queued Paper Orders"
    },
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/paper_worker.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "paper_resolution_evidence": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/paper_settlement.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    },
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/paper_settlement.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "paper_trade_plans": [
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/paper_plans.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "research_captures": [
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/research_capture.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "settings": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/calibration.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "signals": [
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/signal_engine.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "strategy_conflicts": [
    {
      "cadence": "daily",
      "file": "pipeline_intraday.yml",
      "how": "scripts/signal_engine.py",
      "kind": "action",
      "name": "Intraday Pipeline (model, probabilities, edges)"
    }
  ],
  "trades_observed": [
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P0.4_trade_history.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P0.4 - Trade History"
    }
  ],
  "weather_events": [
    {
      "cadence": "only when you run it",
      "file": "live_weather.yml",
      "how": "scripts/live_weather.py",
      "kind": "action",
      "name": "Live Weather Monitor"
    },
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P1.1_live_weather_alerts.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 - P1.1 Live Weather Alerts"
    },
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P1.2_nws_monitor.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P1.2 - NWS Monitor"
    }
  ],
  "weather_forecast_features": [
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P1.4_nws_gridpoint.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P1.4 - NWS Gridpoint"
    },
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P1.5_open_meteo.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P1.5 - Open-Meteo Global"
    }
  ],
  "weather_forecasts": [
    {
      "cadence": "daily",
      "file": "forecasts.yml",
      "how": "scripts/ingest_forecasts.py",
      "kind": "action",
      "name": "Forecasts (Open-Meteo Previous Runs)"
    },
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/ingest_forecasts.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    },
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P1.3_nws_forecast.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P1.3 - NWS Forecast"
    },
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P1.5_open_meteo.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P1.5 - Open-Meteo Global"
    }
  ],
  "weather_observations": [
    {
      "cadence": "only when you run it",
      "file": "live_weather.yml",
      "how": "scripts/live_weather.py",
      "kind": "action",
      "name": "Live Weather Monitor"
    },
    {
      "cadence": "daily",
      "file": "observations.yml",
      "how": "scripts/ingest_observations.py",
      "kind": "action",
      "name": "Observations (IEM METAR)"
    },
    {
      "cadence": "whenever its n8n schedule fires",
      "file": "P1.2_nws_monitor.template.json",
      "how": "n8n",
      "kind": "n8n",
      "name": "AD4 P1.2 - NWS Monitor"
    }
  ],
  "weather_resolution_attempts": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/weather_outcomes.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ],
  "weather_resolution_evidence": [
    {
      "cadence": "daily",
      "file": "pipeline_daily.yml",
      "how": "scripts/weather_outcomes.py",
      "kind": "action",
      "name": "Daily Pipeline (forecasts, settlement, skill, databank, derived)"
    }
  ]
};

/** Which TRACKED TABLES a view ultimately reads.
 *
 * A panel queries a view; the thing that stops being written is a table under
 * it. Without this map an empty panel could only say "this view is empty",
 * leaving the reader to work out which of the tables beneath it went quiet.
 */
export const VIEW_TABLES: Record<string, string[]> = {
  "v_archive_by_city": [
    "bands",
    "book_snapshots",
    "cities",
    "markets",
    "weather_forecasts",
    "weather_observations"
  ],
  "v_archive_daily": [
    "bands",
    "book_snapshots",
    "cities",
    "markets",
    "trades_observed",
    "weather_forecasts",
    "weather_observations"
  ],
  "v_archive_inventory": [
    "bands",
    "book_snapshots",
    "markets",
    "trades_observed",
    "weather_events",
    "weather_forecast_features",
    "weather_forecasts",
    "weather_observations"
  ],
  "v_backtest_window": [
    "bands",
    "book_snapshots",
    "markets",
    "weather_forecasts",
    "weather_observations"
  ],
  "v_band_book": [
    "bands",
    "book_snapshots"
  ],
  "v_band_ladder": [
    "bands",
    "book_snapshots",
    "cities",
    "markets",
    "paper_trades",
    "trades_observed",
    "edges"
  ],
  "v_band_price_history": [
    "bands",
    "book_snapshots",
    "markets",
    "derived_climb_profile",
    "cities",
    "weather_observations"
  ],
  "v_band_volume": [
    "bands",
    "markets",
    "trades_observed"
  ],
  "v_bankroll_curve": [
    "fact_signal_outcome"
  ],
  "v_book_capture_health": [
    "bands",
    "book_snapshots",
    "markets"
  ],
  "v_book_ladder": [
    "bands",
    "book_snapshots"
  ],
  "v_book_target_health": [
    "bands",
    "book_snapshots",
    "markets"
  ],
  "v_calibration": [
    "fact_band_outcome",
    "bands",
    "paper_resolution_evidence",
    "markets"
  ],
  "v_campaign_state": [
    "ledger",
    "cities",
    "fact_signal_outcome",
    "signals",
    "derived_forecast_skill",
    "bands",
    "book_snapshots",
    "markets",
    "paper_trades",
    "trades_observed",
    "edges",
    "derived_weather_peak",
    "live_weather",
    "derived_climb_profile",
    "weather_observations"
  ],
  "v_campaign_targets": [
    "cities"
  ],
  "v_canonical_bands": [
    "bands"
  ],
  "v_canonical_markets": [
    "markets"
  ],
  "v_city_climate": [
    "cities",
    "weather_observations"
  ],
  "v_city_climb_profile": [
    "derived_climb_profile",
    "cities",
    "weather_observations"
  ],
  "v_city_climb_profile_live": [
    "cities",
    "weather_observations"
  ],
  "v_city_daily_max": [
    "cities",
    "weather_observations"
  ],
  "v_city_day_execution_readiness": [
    "band_probabilities",
    "bands",
    "markets",
    "book_snapshots",
    "cities",
    "edges",
    "live_weather",
    "weather_forecasts"
  ],
  "v_city_day_features": [
    "cities",
    "weather_observations"
  ],
  "v_city_day_plan": [
    "bands",
    "book_snapshots",
    "cities",
    "markets",
    "paper_trades",
    "trades_observed",
    "edges",
    "derived_forecast_skill",
    "derived_weather_peak",
    "live_weather",
    "derived_climb_profile",
    "weather_observations"
  ],
  "v_city_day_readiness": [
    "band_probabilities",
    "bands",
    "book_snapshots",
    "cities",
    "edges",
    "live_weather",
    "markets",
    "weather_forecasts"
  ],
  "v_city_metadata_health": [
    "cities"
  ],
  "v_city_metadata_verification": [
    "cities"
  ],
  "v_city_observation_health": [
    "cities",
    "live_weather",
    "weather_observations"
  ],
  "v_city_peak_approach": [
    "derived_climb_profile",
    "cities",
    "weather_observations"
  ],
  "v_city_prediction_confidence": [
    "cities",
    "derived_forecast_skill",
    "bands",
    "fact_band_outcome",
    "markets",
    "edges",
    "band_probabilities",
    "paper_resolution_evidence"
  ],
  "v_city_reasoning": [
    "cities",
    "derived_forecast_skill",
    "derived_weather_model",
    "live_weather",
    "markets",
    "weather_forecasts",
    "derived_city_climate",
    "weather_observations",
    "bands",
    "book_snapshots",
    "paper_trades",
    "trades_observed",
    "edges",
    "derived_city_day_features"
  ],
  "v_city_running_max": [
    "cities",
    "live_weather",
    "weather_observations"
  ],
  "v_city_stats": [
    "cities",
    "derived_capacity",
    "derived_city_climate",
    "derived_forecast_skill",
    "derived_weather_peak",
    "edges",
    "live_weather",
    "weather_observations",
    "bands",
    "markets",
    "trades_observed",
    "weather_forecasts",
    "book_snapshots",
    "paper_trades"
  ],
  "v_city_temp_trend": [
    "cities",
    "weather_observations"
  ],
  "v_city_today_readings": [
    "cities",
    "weather_observations"
  ],
  "v_city_volume": [
    "bands",
    "markets",
    "trades_observed"
  ],
  "v_condition_skill": [
    "derived_city_day_features",
    "weather_forecast_features"
  ],
  "v_databank_coverage": [
    "fact_band_outcome",
    "fact_forecast_outcome",
    "fact_signal_outcome"
  ],
  "v_edge_realisation": [
    "fact_band_outcome",
    "bands",
    "paper_resolution_evidence",
    "markets"
  ],
  "v_edge_scaling": [
    "fact_band_outcome",
    "bands",
    "paper_resolution_evidence",
    "markets"
  ],
  "v_execution_health": [
    "band_probabilities",
    "bands",
    "markets",
    "book_snapshots",
    "cities",
    "edges",
    "live_weather",
    "weather_forecasts"
  ],
  "v_execution_limits": [
    "markets"
  ],
  "v_forecast_audit": [
    "cities",
    "derived_city_climate",
    "weather_forecasts",
    "weather_observations"
  ],
  "v_forecast_candidates": [
    "cities",
    "derived_city_climate",
    "weather_forecasts"
  ],
  "v_forecast_convergence": [
    "fact_forecast_outcome",
    "weather_resolution_evidence",
    "weather_forecasts"
  ],
  "v_forecast_convergence_all": [
    "fact_forecast_outcome",
    "weather_resolution_evidence",
    "weather_forecasts"
  ],
  "v_forecast_coverage": [
    "cities",
    "weather_forecasts"
  ],
  "v_forecast_divergence": [
    "cities",
    "weather_forecasts"
  ],
  "v_forecast_divergence_current": [
    "derived_city_climate",
    "cities",
    "weather_observations",
    "weather_forecasts"
  ],
  "v_forecast_features": [
    "weather_forecast_features"
  ],
  "v_forecast_model_skill": [
    "derived_forecast_skill",
    "derived_forecast_skill_model",
    "weather_forecasts"
  ],
  "v_index_never_used": [
    "bands",
    "book_snapshots",
    "markets",
    "trades_observed",
    "weather_events",
    "weather_forecast_features",
    "weather_forecasts",
    "weather_observations"
  ],
  "v_latest_book": [
    "book_snapshots",
    "bands"
  ],
  "v_latest_edge": [
    "edges"
  ],
  "v_latest_prob": [
    "band_probabilities"
  ],
  "v_learning_state": [
    "cities",
    "derived_forecast_skill",
    "derived_model_forecast",
    "derived_weather_model",
    "fact_forecast_outcome",
    "bands",
    "derived_city_climate",
    "derived_city_day_features",
    "derived_weather_peak",
    "edges",
    "fact_band_outcome",
    "markets",
    "weather_forecasts"
  ],
  "v_model_disagreement": [
    "derived_model_promotion",
    "derived_model_forecast"
  ],
  "v_model_forecast_current": [
    "derived_model_forecast"
  ],
  "v_model_forecast_skill": [
    "derived_city_day_features",
    "derived_model_forecast",
    "derived_weather_model",
    "weather_forecast_features"
  ],
  "v_model_promoted": [
    "derived_model_promotion"
  ],
  "v_model_promotion": [
    "cities",
    "derived_model_promotion"
  ],
  "v_operational_health": [
    "band_probabilities",
    "bands",
    "book_snapshots",
    "cities",
    "edges",
    "live_weather",
    "markets",
    "weather_forecasts"
  ],
  "v_opportunities": [
    "bands",
    "book_snapshots",
    "cities",
    "markets",
    "paper_trades",
    "trades_observed",
    "edges"
  ],
  "v_opportunity_context": [
    "bands",
    "book_snapshots",
    "markets",
    "weather_forecasts"
  ],
  "v_outcome_evidence_health": [
    "fact_band_outcome",
    "fact_forecast_outcome",
    "paper_resolution_evidence",
    "bands",
    "markets",
    "weather_resolution_evidence"
  ],
  "v_paper_desks": [
    "paper_accounts",
    "paper_orders",
    "paper_positions"
  ],
  "v_peak_hour_coverage": [
    "cities",
    "derived_weather_peak"
  ],
  "v_persistence_skill": [
    "derived_city_day_features",
    "cities",
    "weather_observations"
  ],
  "v_prediction_ladder": [
    "bands",
    "fact_band_outcome",
    "markets",
    "edges",
    "band_probabilities",
    "paper_resolution_evidence"
  ],
  "v_prediction_scorecard": [
    "fact_forecast_outcome",
    "weather_resolution_evidence"
  ],
  "v_prediction_scorecard_all": [
    "fact_forecast_outcome",
    "weather_resolution_evidence"
  ],
  "v_sigma_inputs": [
    "cities",
    "derived_calibration_adjustment",
    "derived_forecast_skill"
  ],
  "v_signal_outcome": [
    "fact_band_outcome",
    "fact_signal_outcome"
  ],
  "v_signal_scorecard": [
    "fact_band_outcome",
    "fact_signal_outcome"
  ],
  "v_signal_scorecard_by_version": [
    "fact_band_outcome",
    "fact_signal_outcome"
  ],
  "v_storage_report": [
    "cities",
    "derived_city_day_features",
    "weather_observations"
  ],
  "v_strategy_board": [
    "fact_signal_outcome",
    "signals"
  ],
  "v_synthesis_findings": [
    "bands",
    "derived_city_climate",
    "derived_city_day_features",
    "derived_weather_peak",
    "edges",
    "fact_band_outcome",
    "fact_forecast_outcome",
    "markets",
    "weather_forecasts"
  ],
  "v_trade_plan": [
    "derived_forecast_skill",
    "bands",
    "book_snapshots",
    "cities",
    "markets",
    "paper_trades",
    "trades_observed",
    "edges",
    "derived_weather_peak",
    "live_weather",
    "derived_climb_profile",
    "weather_observations"
  ],
  "v_trade_timing": [
    "cities",
    "derived_weather_peak",
    "live_weather",
    "derived_climb_profile",
    "weather_observations"
  ],
  "v_venue_band_resolution": [
    "bands",
    "paper_resolution_evidence"
  ],
  "v_venue_market_resolution": [
    "bands",
    "markets",
    "paper_resolution_evidence"
  ],
  "v_verified_fact_band_outcome": [
    "bands",
    "fact_band_outcome",
    "paper_resolution_evidence",
    "markets"
  ],
  "v_verified_fact_forecast_outcome": [
    "fact_forecast_outcome",
    "weather_resolution_evidence"
  ],
  "v_verified_weather_outcomes": [
    "weather_resolution_evidence"
  ],
  "v_weather_effects": [
    "derived_city_day_features",
    "cities",
    "weather_observations"
  ],
  "v_weather_resolution_collection_health": [
    "weather_resolution_attempts"
  ],
  "v_workflow_runs": [
    "ingest_log"
  ]
};

/** The tracked tables behind any relation, view or table alike. */
export function tablesBehind(relation: string): string[] {
  const r = relation.toLowerCase();
  if (VIEW_TABLES[r]) return VIEW_TABLES[r];
  return FILLED_BY[r] ? [r] : [];
}

/** Every job that fills this relation, or [] if nothing in the repo does. */
export function fillersFor(relation: string): Filler[] {
  const direct = FILLED_BY[relation.toLowerCase()];
  if (direct) return direct;
  const out: Filler[] = [];
  for (const t of tablesBehind(relation)) {
    for (const f of FILLED_BY[t] ?? []) {
      if (!out.some((e) => e.file === f.file && e.kind === f.kind)) out.push(f);
    }
  }
  return out;
}

/** One sentence naming who fills it and how often, or null if nothing does. */
export function whoFills(relation: string): string | null {
  const f = fillersFor(relation);
  if (!f.length) return null;
  const where = f[0].kind === "action" ? "the GitHub Action" : "the n8n workflow";
  const rest = f.length > 1 ? ` (and ${f.length - 1} more)` : "";
  return `Filled by ${where} \u201c${f[0].name}\u201d, ${f[0].cadence}${rest}.`;
}
