// Assertions for web/lib/units.ts and web/lib/time.ts, run with Node's
// type-stripping so no test-runner dependency is added to the web app.
//
// These two modules decide what every temperature and every timestamp in the
// UI says. The bugs they exist to prevent are the quiet kind: a Fahrenheit
// market printed in Celsius reads as a plausible number, and a delta
// converted with the +32 offset reads as a plausible number too.
import assert from "node:assert/strict";
import * as U from "../../web/lib/units.ts";
import * as T from "../../web/lib/time.ts";

const out = [];
function t(name, fn) {
  try { fn(); out.push(["ok", name]); }
  catch (e) { out.push(["FAIL", name + " :: " + e.message]); }
}

// ---- units ---------------------------------------------------------------
t("US city shows Fahrenheit", () => {
  assert.equal(U.fmtTemp(28.3, "F"), "82.9°F");
});
t("metric city still shows Celsius", () => {
  assert.equal(U.fmtTemp(28.3, "C"), "28.3°C");
});
t("a missing unit does not invent Fahrenheit", () => {
  assert.equal(U.fmtTemp(28.3, null), "28.3°C");
});
t("a DELTA converts by ratio, never by offset", () => {
  // The bug this exists for: 1°C of change is 1.8°F, not 33.8°F. An offset
  // applied to a delta turns every sigma and every hourly change into noise.
  assert.equal(U.deltaToDisplay(1, "F"), 1.8);
  assert.equal(U.fmtTempDelta(1, "F"), "+1.8°F");
  assert.equal(U.fmtTempDelta(-0.5, "F"), "-0.9°F");
  assert.equal(U.fmtTempDelta(1, "C"), "+1.0°C");
});
t("band edges round to how the market quotes them", () => {
  // 21.11C is exactly 70F: an F market must show 70, not 69.998 or 21.1
  assert.equal(U.fmtBandEdge(U.fToC(70), "F"), "70");
  assert.equal(U.fmtBandEdge(U.fToC(78), "F"), "78");
  // C markets quote in halves, and halves are exactly representable, so this
  // is the case that actually occurs - not a contrived .x5 rounding edge.
  assert.equal(U.fmtBandEdge(21.5, "C"), "21.5");
  assert.equal(U.fmtBandEdge(22, "C"), "22.0");
});
t("a band reads as the interval the market states", () => {
  assert.equal(U.fmtBandRange(U.fToC(70), U.fToC(72), "F"), "70–72°F");
  assert.equal(U.fmtBandRange(null, U.fToC(60), "F", true, false), "≤ 60°F");
  assert.equal(U.fmtBandRange(U.fToC(78), null, "F", false, true), "≥ 78°F");
});
t("round trip C -> F -> C", () => {
  assert.ok(Math.abs(U.fToC(U.cToF(23.7)) - 23.7) < 1e-9);
});
t("null temperature is a dash, not NaN", () => {
  assert.equal(U.fmtTemp(null, "F"), "—");
  assert.equal(U.fmtTempDelta(undefined, "F"), "—");
});

// ---- time ----------------------------------------------------------------
t("timestamps render in the viewer's zone, not UTC", () => {
  const iso = "2026-09-03T19:30:00Z";
  assert.equal(T.fmtTime(iso, "Asia/Beirut"), "22:30");   // UTC+3 in September
  assert.equal(T.fmtTime(iso, "UTC"), "19:30");
});
t("a resolution date is a calendar day, never shifted by a zone", () => {
  // Shifting it would rename the day: 2026-09-03 in a UTC-6 zone is not 2 Sep.
  assert.equal(T.fmtResolutionDate("2026-09-03"), "Thu 3 Sep");
});
t("days ahead is what a trader says", () => {
  const today = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Beirut", year: "numeric", month: "2-digit", day: "2-digit",
  }).format(new Date());
  const plus = (n) => {
    const d = new Date(today + "T00:00:00Z");
    d.setUTCDate(d.getUTCDate() + n);
    return d.toISOString().slice(0, 10);
  };
  assert.equal(T.daysAhead(today, "Asia/Beirut"), 0);
  assert.equal(T.fmtDaysAhead(today, "Asia/Beirut"), "today");
  assert.equal(T.fmtDaysAhead(plus(1), "Asia/Beirut"), "tomorrow");
  assert.equal(T.fmtDaysAhead(plus(2), "Asia/Beirut"), "in 2 days");
  assert.equal(T.fmtDaysAhead(plus(-1), "Asia/Beirut"), "yesterday");
});
t("a city peak hour shows both clocks", () => {
  // Chicago's 15:00 peak, read from Beirut. CDT is UTC-5 in September,
  // Beirut UTC+3 - eight hours, so 23:00 the same evening.
  const s = T.fmtCityHour(15, "America/Chicago", "Asia/Beirut");
  assert.ok(s.startsWith("15:00"), s);
  assert.ok(s.includes("23:00"), s);
  assert.ok(s.includes("your time"), s);
});
t("same zone does not print a redundant second clock", () => {
  const s = T.fmtCityHour(15, "Asia/Beirut", "Asia/Beirut");
  assert.ok(!s.includes("your time"), s);
});
t("a half-hour peak keeps its minutes", () => {
  assert.ok(T.fmtCityHour(15.5, "America/Chicago", "Asia/Beirut").startsWith("15:30"));
});
t("bad input degrades to a dash, never a crash", () => {
  assert.equal(T.fmtTime(null, "UTC"), "—");
  assert.equal(T.fmtTime("not a date", "UTC"), "—");
  assert.equal(T.fmtCityHour(null, "UTC"), "—");
});

// ---- costs ---------------------------------------------------------------
// Ported from scripts/cost_model.py. The port is only worth anything if it
// agrees with the original, so the expected values below are generated by the
// Python module itself in tests/test_web_display.py and passed in via argv.
import * as C from "../../web/lib/costs.ts";

t("taker fee has the p(1-p) shape, not a flat rate", () => {
  // Peaks at p=0.5 and vanishes at both ends - a flat percentage has neither
  // property, and would overstate the cost of every cheap tail.
  assert.ok(Math.abs(C.takerFee(100, 0.5) - 100 * 0.05 * 0.25) < 1e-12);
  assert.ok(C.takerFee(100, 0.5) > C.takerFee(100, 0.9));
  assert.ok(C.takerFee(100, 0.5) > C.takerFee(100, 0.1));
  assert.ok(Math.abs(C.takerFee(100, 1.0)) < 1e-12);
  assert.ok(Math.abs(C.takerFee(100, 0.0)) < 1e-12);
});
t("a stake is what leaves the account, fee included", () => {
  const p = C.buy(100, 0.34);
  assert.ok(p);
  assert.ok(Math.abs(p.cost - 100) < 1e-9);              // exactly $100 at risk
  // shares x price + fee should reconstitute the stake
  const spent = p.shares * 0.34 + p.fee;
  assert.ok(Math.abs(spent - 100) < 1e-6, `spent ${spent}`);
});
t("a losing band loses the whole stake", () => {
  assert.equal(C.buy(100, 0.34).loss, -100);
});
t("EV is signed correctly around the price", () => {
  // model says 47% on a 34c band -> positive; model says 20% -> negative
  assert.ok(C.buy(100, 0.34, 0.47).ev > 0);
  assert.ok(C.buy(100, 0.34, 0.20).ev < 0);
  assert.equal(C.buy(100, 0.34, null).ev, null);
});
t("a maker pays nothing", () => {
  assert.equal(C.buy(100, 0.34, null, false).fee, 0);
  assert.ok(C.buy(100, 0.34, null, false).shares > C.buy(100, 0.34, null, true).shares);
});
t("nonsense input returns null, never a number", () => {
  assert.equal(C.buy(0, 0.5), null);
  assert.equal(C.buy(-5, 0.5), null);
  assert.equal(C.buy(100, 0), null);
  assert.equal(C.buy(100, 1), null);
  assert.equal(C.buy(100, NaN), null);
});

// ---- monte carlo ---------------------------------------------------------
import * as MC from "../../web/lib/montecarlo.ts";

const ladder = (stakes = {}) => {
  // 9 one-degree bands 20..29 plus two open tails, like a Celsius city
  const bs = [{ band_id: "lo", label: "<20", lo: null, hi: 20, price: 0.05, stake: stakes.lo ?? 0 }];
  for (let t = 20; t < 29; t++) {
    bs.push({ band_id: `b${t}`, label: `${t}-${t + 1}`, lo: t, hi: t + 1, price: 0.1, stake: stakes[`b${t}`] ?? 0 });
  }
  bs.push({ band_id: "hi", label: "29+", lo: 29, hi: null, price: 0.05, stake: stakes.hi ?? 0 });
  return bs;
};

t("the simulated distribution matches the analytic one", () => {
  // Centre 24.5 with sigma 1: band [24,25) should take ~38% of draws
  // (Phi(0.5) - Phi(-0.5) = 0.3829). The engine integrates this analytically;
  // if the simulation disagrees, one of the two is wrong.
  const r = MC.simulate(24.5, 1.0, ladder(), 40000);
  const b24 = r.landed.find((l) => l.band_id === "b24");
  assert.ok(Math.abs(b24.share - 0.3829) < 0.01, `b24 share ${b24.share}`);
  const total = r.landed.reduce((s, l) => s + l.share, 0) + r.offLadder;
  assert.ok(Math.abs(total - 1) < 1e-9, `shares sum to ${total}`);
});
t("a wider sigma spreads the mass, it does not move it", () => {
  const tight = MC.simulate(24.5, 0.5, ladder(), 40000);
  const wide = MC.simulate(24.5, 3.0, ladder(), 40000);
  const s = (r) => r.landed.find((l) => l.band_id === "b24").share;
  assert.ok(s(tight) > s(wide), "a tighter forecast must concentrate more mass");
  assert.ok(wide.landed.filter((l) => l.share > 0.01).length > tight.landed.filter((l) => l.share > 0.01).length);
});
t("the same seed gives the same picture twice", () => {
  const a = MC.simulate(24.5, 1.2, ladder({ b24: 100 }), 5000, 7);
  const b = MC.simulate(24.5, 1.2, ladder({ b24: 100 }), 5000, 7);
  assert.equal(a.mean, b.mean);
  assert.equal(a.p5, b.p5);
});
t("a single losing leg loses exactly the stake", () => {
  // centre far below the band bought: it essentially never hits
  const r = MC.simulate(20.0, 0.5, ladder({ b28: 100 }), 5000);
  assert.ok(Math.abs(r.worst + 100) < 1e-9, `worst ${r.worst}`);
  assert.ok(r.probProfit < 0.01);
});
t("a leg that always hits returns the payout less the stake", () => {
  const r = MC.simulate(24.5, 0.01, ladder({ b24: 100 }), 5000);
  assert.ok(r.probProfit > 0.99);
  // 100 at 10c, fee taken from the stake -> payout ~ 917 shares
  assert.ok(r.best > 800, `best ${r.best}`);
});
t("P&L quantiles are ordered", () => {
  const r = MC.simulate(24.5, 1.5, ladder({ b24: 60, b25: 40 }), 20000);
  assert.ok(r.worst <= r.p5);
  assert.ok(r.p5 <= r.median);
  assert.ok(r.median <= r.p95);
  assert.ok(r.p95 <= r.best);
});
t("mass off the ladder is counted, not silently dropped", () => {
  // centre far above the top band: almost everything lands off-ladder... except
  // the open-high tail catches it, which is what an open tail is FOR.
  const noTails = ladder().filter((b) => b.lo !== null && b.hi !== null);
  const r = MC.simulate(40, 1.0, noTails, 5000);
  assert.ok(r.offLadder > 0.99, `offLadder ${r.offLadder}`);
  const withTails = MC.simulate(40, 1.0, ladder(), 5000);
  assert.ok(withTails.offLadder < 0.01);
});
t("the histogram covers every sample", () => {
  const r = MC.simulate(24.5, 1.5, ladder({ b24: 100 }), 10000);
  const h = MC.histogram(r.pnl, 20);
  assert.equal(h.reduce((s, b) => s + b.value, 0), r.pnl.length);
});

// ---- board ladder --------------------------------------------------------
import * as LAD from "../../web/lib/ladder.ts";

const legs = (over = {}) => ["a", "b", "c"].map((id, i) => ({
  band_id: id, label: `bucket ${id}`,
  yesPrice: [0.2, 0.5, 0.3][i], noPrice: [0.8, 0.5, 0.7][i],
  depthUsd: null, yesStake: 0, noStake: 0, ...(over[id] ?? {}),
}));

t("exactly one bucket pays, and the ladder says so", () => {
  const r = LAD.solveBoard(legs({ b: { yesStake: 100 } }));
  assert.equal(r.outcomes.length, 3);
  const win = r.outcomes.find((o) => o.band_id === "b");
  const lose = r.outcomes.filter((o) => o.band_id !== "b");
  assert.ok(win.pnl > 0, `win ${win.pnl}`);
  assert.ok(lose.every((o) => Math.abs(o.pnl + 100) < 1e-9), "every other bucket loses the stake");
});

t("a NO leg pays on every bucket except its own", () => {
  // This is the case a per-row calculation cannot show: one stake, three rows.
  const r = LAD.solveBoard(legs({ b: { noStake: 100 } }));
  const own = r.outcomes.find((o) => o.band_id === "b");
  const others = r.outcomes.filter((o) => o.band_id !== "b");
  assert.ok(Math.abs(own.pnl + 100) < 1e-9, `own bucket must lose the stake, got ${own.pnl}`);
  assert.ok(others.every((o) => o.pnl > 0), "every other bucket pays");
});

t("a full set of YES legs is a locked ticket when it costs under par", () => {
  // 20 + 50 + 30 = 100c exactly; with fees it is over par, so NOT locked.
  const fair = LAD.solveBoard(legs({ a: { yesStake: 20 }, b: { yesStake: 50 }, c: { yesStake: 30 } }));
  assert.ok(!fair.locked, "a book at exactly par cannot be locked once fees are paid");
  // Now underprice the set: 15 + 45 + 25 = 85c. Buying proportionally locks it.
  const cheap = [
    { band_id: "a", label: "a", yesPrice: 0.15, noPrice: 0.85, depthUsd: null, yesStake: 15, noStake: 0 },
    { band_id: "b", label: "b", yesPrice: 0.45, noPrice: 0.55, depthUsd: null, yesStake: 45, noStake: 0 },
    { band_id: "c", label: "c", yesPrice: 0.25, noPrice: 0.75, depthUsd: null, yesStake: 25, noStake: 0 },
  ];
  const r = LAD.solveBoard(cheap);
  assert.ok(r.locked, `an 85c set must lock, worst was ${r.worst}`);
  assert.ok(r.worst > 0);
});

t("depth caps a stake instead of pretending it filled", () => {
  const r = LAD.solveBoard(legs({ b: { yesStake: 500, depthUsd: 80 } }));
  assert.ok(r.anyCapped);
  assert.ok(Math.abs(r.cost - 80) < 1e-9, `cost ${r.cost} should be the depth, not the stake`);
  assert.equal(r.requested, 500);
});

t("EV needs every bucket to have a probability", () => {
  const staked = legs({ b: { yesStake: 100 } });
  assert.equal(LAD.solveBoard(staked).ev, null);
  const partial = new Map([["a", 0.2], ["b", 0.5]]);
  assert.equal(LAD.solveBoard(staked, partial).ev, null, "a missing bucket must not be treated as zero");
  const all = new Map([["a", 0.2], ["b", 0.5], ["c", 0.3]]);
  const ev = LAD.solveBoard(staked, all).ev;
  assert.ok(ev !== null && Math.abs(ev) < 100, `ev ${ev}`);
});

t("overround is the book's edge over the punter", () => {
  assert.ok(Math.abs(LAD.overround(legs()) - 1.0) < 1e-9);
  const fat = legs(); fat[0].yesPrice = 0.3;
  assert.ok(LAD.overround(fat) > 1);
  assert.equal(LAD.overround([legs()[0]]), null, "one bucket is not a book");
});

t("an empty board is zero, not NaN", () => {
  const r = LAD.solveBoard(legs());
  assert.equal(r.cost, 0);
  assert.ok(r.outcomes.every((o) => o.pnl === 0));
  assert.ok(!r.locked, "a ticket with nothing on it is not a lock");
});

const failed = out.filter(([s]) => s === "FAIL");
for (const [s, n] of out) if (s === "FAIL") console.log("  FAIL", n);
console.log(JSON.stringify({ ok: failed.length === 0, passed: out.length - failed.length, failed: failed.length }));
