#!/usr/bin/env python3
"""The files a pull request can change without the test suite running.

WXPredict build, wave A.2 (docs/WXPREDICT_BUILD.md, section 3.6, "A.1 result").
A pull request that changes only documents no test reads does not run the
suites. Measured 5 Oct: in October 2 of 53 pull-request runs (10 billed
minutes) changed only such documents. Everything else runs, whatever it is:
the list names what may be skipped, never what is run.

What may be skipped, and only this:
  - files under docs/, except the documents a test opens;
  - markdown files at the repository's root (CLAUDE.md, README.md).

THE JOB ALWAYS RUNS; ITS STEPS DECIDE. A `paths:` filter on the workflow would
leave a docs-only pull request with no `pytest` check at all, which blocks the
merge wherever that check is required (Codex on #315). So tests.yml's first
step runs `--decide`: it reads the pull request's own diff (the merge commit
against its first parent, the base) and every later step runs only when a
changed file is one the suites may read. A docs-only pull request reports a
green `pytest` in seconds; any doubt - not a pull request, no merge commit, git
failing - runs everything.

Which documents a test opens is MEASURED, not listed by hand: `--write` runs
the whole Python suite with the recorder in tests/conftest.py (which also
instruments the Python and Node processes the tests start) and writes what it
saw into .github/ci-paths.txt. Two things hold it:
  - tests/conftest.py fails the run when a test, or a process it starts, opens
    or lists a path the list skips, or names one on another child's command line;
  - tests/test_ci_paths.py checks the file is this module's rendering, that
    every tracked file outside the skippable set still runs the suites, and
    that no node test names a skipped document.

The patterns read as GitHub's path filters do: in order, the last pattern that
matches a file decides it; the suites run when any changed file is included.

    python3 tools/ci_paths.py --write             # after a test starts reading a doc
    python3 tools/ci_paths.py --decide <event>    # tests.yml's first step
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATTERNS = os.path.join(ROOT, ".github", "ci-paths.txt")
RECORD_ENV = "AD4_CI_PATHS_RECORD"
HEADER = """# GENERATED by `python3 tools/ci_paths.py --write`: do not edit by hand.
# A pull request runs the test suites unless every file it changes ends up
# excluded here (WXPredict build A.2). Read in order, the last match decides:
# `**` crosses directories, `*` does not, `!` excludes. tests/conftest.py fails
# the suite if a test reads a file this list excludes.
"""


def skippable(rel):
    """Is this repository path one the list may skip (before re-includes)?"""
    rel = rel.replace(os.sep, "/")
    if rel.startswith("docs/"):
        return True
    return "/" not in rel and rel.endswith(".md")


def patterns(read_docs):
    """The patterns, in order (the last match decides)."""
    return ["**", "!*.md", "!docs/**"] + sorted(set(read_docs))


def render(read_docs):
    return HEADER + "".join(f"{p}\n" for p in patterns(read_docs))


def read_block(text=None):
    """The patterns as they stand in .github/ci-paths.txt."""
    if text is None:
        text = open(PATTERNS, encoding="utf-8").read()
    return [l.strip() for l in text.splitlines() if l.strip() and not l.lstrip().startswith("#")]


def included_docs(block=None):
    """The skippable paths the list puts back: the documents a test reads."""
    block = read_block() if block is None else block
    return {p for p in block if not p.startswith("!") and skippable(p) and "*" not in p}


def _glob_re(pat):
    """GitHub's filter glob: ** crosses '/', * and ? do not."""
    out, i = "", 0
    while i < len(pat):
        if pat.startswith("**", i):
            out += ".*"
            i += 2
        elif pat[i] == "*":
            out += "[^/]*"
            i += 1
        elif pat[i] == "?":
            out += "[^/]"
            i += 1
        else:
            out += re.escape(pat[i])
            i += 1
    return re.compile(out + r"\Z")


def runs_for(path, block=None):
    """Would a pull request changing only `path` run the suites?"""
    block = read_block() if block is None else block
    included = False
    for p in block:
        neg = p.startswith("!")
        if _glob_re(p[1:] if neg else p).match(path):
            included = not neg
    return included


def decide(event, changed, block=None):
    """(run, why) for one workflow run. Anything but a clean docs-only pull
    request runs everything."""
    if event != "pull_request":
        return True, f"a {event or 'manual'} run: everything runs"
    if changed is None:
        return True, "the pull request's diff could not be read: everything runs"
    if not changed:
        return True, "the diff names no file: everything runs"
    block = read_block() if block is None else block
    hits = [f for f in changed if runs_for(f, block)]
    if hits:
        return True, f"{len(hits)} of {len(changed)} changed file(s) can reach a test, e.g. {hits[0]}"
    return False, (f"only documents no test reads changed ({len(changed)}): "
                   + ", ".join(sorted(changed)[:10]))


def pr_diff(root=ROOT):
    """The files a pull request changes: its merge commit against the base
    (first parent). None when that cannot be read for certain."""
    try:
        parents = subprocess.run(["git", "-C", root, "rev-list", "--parents", "-n", "1", "HEAD"],
                                 capture_output=True, text=True, timeout=60)
        if parents.returncode != 0 or len(parents.stdout.split()) != 3:
            return None           # not the two-parent merge GitHub checks out for a pull request
        out = subprocess.run(["git", "-C", root, "diff", "--name-only", "HEAD^1", "HEAD"],
                             capture_output=True, text=True, timeout=120)
        if out.returncode != 0:
            return None
        return [l for l in out.stdout.splitlines() if l]
    except (OSError, subprocess.SubprocessError):
        return None


def violations(read_paths, listed_dirs, commands=(), block=None):
    """Paths a test touched that a pull request could change without a run."""
    block = read_block() if block is None else block
    bad = sorted(p for p in read_paths if skippable(p) and not runs_for(p, block))
    bad += sorted(f"{d}/ (listed)" for d in listed_dirs if d == "docs" or d.startswith("docs/"))
    for cmd in commands:
        for m in re.finditer(r"(?<![\w./-])((?:docs/[\w./-]+)|(?:[\w.-]+\.md))(?![\w./-])", cmd):
            name = m.group(1)
            if skippable(name) and not runs_for(name, block):
                bad.append(f"{name} (named by a child process: {cmd[:80]!r})")
    return bad


def write(read_docs):
    with open(PATTERNS, "w", encoding="utf-8") as f:
        f.write(render(read_docs))


def main(argv):
    if argv[1:2] == ["--decide"]:
        event = argv[2] if len(argv) > 2 else ""
        run, why = decide(event, pr_diff() if event == "pull_request" else [])
        print(("RUN: " if run else "SKIP: ") + why)
        out = os.environ.get("GITHUB_OUTPUT")
        if out:
            with open(out, "a", encoding="utf-8") as f:
                f.write(f"run={'true' if run else 'false'}\n")
        return 0
    if argv[1:] != ["--write"]:
        print(__doc__)
        return 2
    out = os.path.join(ROOT, ".pytest_cache", "ci_paths_record.txt")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    if os.path.exists(out):
        os.remove(out)
    env = dict(os.environ, PYTHONPATH="scripts", **{RECORD_ENV: out})
    rc = subprocess.call([sys.executable, "-m", "pytest", "tests/", "-q"], cwd=ROOT, env=env)
    if rc != 0 or not os.path.exists(out):
        print(f"the suite did not pass (exit {rc}); nothing written")
        return 1
    docs = [l.strip() for l in open(out, encoding="utf-8") if l.strip()]
    write(docs)
    print(f".github/ci-paths.txt: {len(docs)} documents put back: {', '.join(sorted(docs)) or 'none'}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
