#!/usr/bin/env python3
"""The files a pull request can change without the test suite running.

WXPredict build, wave A.2 (docs/WXPREDICT_BUILD.md, section 3.6, "A.1 result").
`tests.yml` runs on a pull request only when the pull request changes a file
some test reads. Measured 5 Oct: in October 2 of 53 pull-request runs (10
billed minutes) changed only documents no test opens. Everything else runs,
whatever it is: the filter names what is skipped, never what is run.

What is skipped, and only this:
  - files under docs/, except the documents a test opens;
  - markdown files at the repository's root (CLAUDE.md, README.md).

Which documents a test opens is MEASURED, not listed by hand: `--write` runs
the whole Python suite with the recorder in tests/conftest.py switched on and
writes what it saw into the `paths:` block of tests.yml. Two things hold it:
  - tests/conftest.py fails the run when a test opens or lists a path the
    filter skips (a test that starts reading a skipped document);
  - tests/test_ci_paths.py checks the block is this module's rendering, that
    every tracked file outside the skipped set still runs the suite, and that
    no node test names a skipped document.

GitHub evaluates a pull request's `paths` over the pull request's whole diff,
in order: the last pattern that matches a file decides it. The workflow runs
when any changed file ends up included.

    python3 tools/ci_paths.py --write    # after a test starts reading a doc
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKFLOW = os.path.join(ROOT, ".github", "workflows", "tests.yml")
BEGIN = "      # BEGIN generated by tools/ci_paths.py --write: do not edit by hand"
END = "      # END generated by tools/ci_paths.py"
RECORD_ENV = "AD4_CI_PATHS_RECORD"


def skippable(rel):
    """Is this repository path one the filter may skip (before re-includes)?"""
    rel = rel.replace(os.sep, "/")
    if rel.startswith("docs/"):
        return True
    return "/" not in rel and rel.endswith(".md")


def patterns(read_docs):
    """The `paths:` patterns, in GitHub's order (the last match decides)."""
    out = ["**", ".github/**", "!*.md", "!docs/**"]
    out += sorted(set(read_docs))
    return out


def render(read_docs):
    lines = [BEGIN]
    lines += [f"      - '{p}'" for p in patterns(read_docs)]
    lines.append(END)
    return "\n".join(lines)


def read_block(text=None):
    """The generated patterns as they stand in tests.yml."""
    if text is None:
        text = open(WORKFLOW, encoding="utf-8").read()
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < i:
        raise ValueError("tests.yml has no generated paths block")
    body = text[i + len(BEGIN):j]
    return [m.group(1) for m in re.finditer(r"^\s*-\s*'([^']*)'\s*$", body, re.M)]


def included_docs(block=None):
    """The skippable paths the filter re-includes: the documents a test reads."""
    block = read_block() if block is None else block
    return {p for p in block if not p.startswith("!") and skippable(p) and "*" not in p}


def _glob_re(pat):
    """GitHub's filter glob: ** crosses '/', * and ? do not."""
    out, i = "", 0
    while i < len(pat):
        if pat.startswith("**", i):
            out += ".*"
            i += 2
        elif pat[i] == "*":
            out += "[^/]*"
            i += 1
        elif pat[i] == "?":
            out += "[^/]"
            i += 1
        else:
            out += re.escape(pat[i])
            i += 1
    return re.compile(out + r"\Z")


def runs_for(path, block=None):
    """Would a pull request changing only `path` run the suite?"""
    block = read_block() if block is None else block
    included = False
    for p in block:
        neg = p.startswith("!")
        if _glob_re(p[1:] if neg else p).match(path):
            included = not neg
    return included


def violations(read_paths, listed_dirs, block=None):
    """Paths a test touched that a pull request could change without a run."""
    block = read_block() if block is None else block
    bad = sorted(p for p in read_paths if skippable(p) and not runs_for(p, block))
    bad += sorted(f"{d}/ (listed)" for d in listed_dirs
                  if d == "docs" or d.startswith("docs/"))
    return bad


def write(read_docs):
    text = open(WORKFLOW, encoding="utf-8").read()
    i, j = text.find(BEGIN), text.find(END)
    new = text[:i] + render(read_docs) + text[j + len(END):]
    with open(WORKFLOW, "w", encoding="utf-8") as f:
        f.write(new)


def main(argv):
    if argv[1:] != ["--write"]:
        print(__doc__)
        return 2
    out = os.path.join(ROOT, ".pytest_cache", "ci_paths_record.txt")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    if os.path.exists(out):
        os.remove(out)
    env = dict(os.environ, PYTHONPATH="scripts", **{RECORD_ENV: out})
    rc = subprocess.call([sys.executable, "-m", "pytest", "tests/", "-q"],
                         cwd=ROOT, env=env)
    if rc != 0 or not os.path.exists(out):
        print(f"the suite did not pass (exit {rc}); nothing written")
        return 1
    docs = [l.strip() for l in open(out, encoding="utf-8") if l.strip()]
    write(docs)
    print(f"tests.yml: {len(docs)} documents re-included: {', '.join(sorted(docs)) or 'none'}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
