#!/usr/bin/env python3
"""Regenerate web/lib/sqlOwner.ts AND sql/ad4_98_ui_health.sql from sql/*.sql.

A missing-relation error should name the file that creates it. Hand-listing
that mapping guarantees it goes stale, so it is derived, and both consumers
are generated from the same pass:

  web/lib/sqlOwner.ts     the browser, so a red box says which file to run
  sql/ad4_98_ui_health.sql  one query that lists EVERY missing relation, the
                            file that creates it, and the pages it makes red

Run this after adding a SQL file or a new query in a page.
tests/test_ui_contracts.py asserts both are current.
"""
import glob, json, os, re

# Words that can only ever be a mis-parse: a comment saying "create table if
# not exists" produced a relation literally named `if`, which then told the UI
# that a page was broken because a table called "if" was missing.
NOT_A_NAME = {"if", "not", "exists", "only", "or", "replace", "temp", "unlogged",
              "table", "view", "materialized", "global", "local", "unique"}


def _strip_comments(src: str) -> str:
    """Line comments and block comments never declare anything."""
    src = re.sub(r"/\*.*?\*/", " ", src, flags=re.S)
    src = re.sub(r"--[^\n]*", " ", src)
    return src


def build() -> dict:
    owner = {}
    for f in sorted(glob.glob(os.path.join(os.path.dirname(__file__), "..", "sql", "*.sql"))):
        src = _strip_comments(open(f).read())
        base = os.path.basename(f)
        for pat in (r"create\s+(?:or\s+replace\s+)?(?:materialized\s+)?view\s+(?:if\s+not\s+exists\s+)?([a-z0-9_]+)",
                    r"create\s+table\s+(?:if\s+not\s+exists\s+)?([a-z0-9_]+)"):
            for m in re.finditer(pat, src, re.I):
                name = m.group(1).lower()
                if name in NOT_A_NAME:
                    continue
                owner.setdefault(name, base)
    return owner

def render(owner: dict) -> str:
    return ("// GENERATED by tools/gen_sql_owner.py - do not edit by hand.\n"
            "//\n"
            "// Which SQL file creates which relation. A missing-relation error used to say\n"
            '// "run sql/ad4_00_preflight.sql", which is right about one file in thirty and\n'
            "// wrong about the one you actually need: every Predictive panel failed on a\n"
            "// view created by ad4_31 and told the reader to run preflight.\n"
            "export const SQL_OWNER: Record<string, string> = "
            + json.dumps(owner, indent=2, sort_keys=True) + ";\n")

def pages_by_relation() -> dict:
    """Which page or component reads each relation, from the app's own source.

    So the health report can say "Opportunities goes red" rather than only
    "a view is missing" - the operator is looking at a page, not at a schema.
    """
    root = os.path.join(os.path.dirname(__file__), "..")
    out = {}
    paths = (glob.glob(os.path.join(root, "web", "app", "**", "page.tsx"), recursive=True)
             + glob.glob(os.path.join(root, "web", "components", "*.tsx")))
    for path in sorted(paths):
        rel = os.path.relpath(path, os.path.join(root, "web"))
        if rel.startswith("components"):
            label = "(" + os.path.basename(path).replace(".tsx", "") + ")"
        else:
            label = "/" + os.path.dirname(rel).replace("app", "").strip("/")
        body = open(path).read()
        for r in set(re.findall(r'\.from\("([a-z_0-9]+)"\)', body)) | set(re.findall(r'\.rpc\("([a-z_0-9]+)"', body)):
            out.setdefault(r, set()).add(label)
    return {k: sorted(v) for k, v in out.items()}


HEALTH_HEAD = """-- ===========================================================================
-- ad4_98_ui_health.sql - WHY IS THE UI SHOWING RED BOXES?
--
-- GENERATED by tools/gen_sql_owner.py from the app's own source. Do not edit.
--
-- READ-ONLY. It creates nothing and changes nothing. Run it any time.
--
-- A RED box on an AD4 page is one thing: a query that failed, almost always
-- because the view behind it does not exist yet. This checks every relation
-- and function the app reads - %d of them - and for each MISSING one names the
-- SQL file that creates it and the pages that go red without it.
--
-- An EMPTY box (dashed border, grey text, naming a job to run) is NOT a fault
-- and NOT a red box: the view exists and has no rows yet because the job that
-- fills it has not run. Those are listed separately at the end.
-- ===========================================================================

"""


def render_health(owner: dict, pages: dict) -> str:
    def q(s):
        return "'" + s.replace("'", "''") + "'"
    rows = [(rel, own, ", ".join(pages.get(rel, []))) for rel, own in sorted(owner.items())]
    values = ",\n    ".join("(%s, %s, %s)" % (q(r), q(o), q(u)) for r, o, u in rows)
    body = """with expected(rel, owner, used_by) as (values
    {V}
),
checked as (
  select e.*,
         (to_regclass('public.' || e.rel) is not null) as is_relation,
         exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                  where n.nspname = 'public' and p.proname = e.rel) as is_function
    from expected e
)
select
  rel                     as missing_relation,
  owner                   as run_this_file,
  nullif(used_by, '')     as pages_that_go_red
from checked
where not (is_relation or is_function)
order by owner, rel;


do $ad4$
declare v_missing int; v_files text; v_empty int; r record;
begin
  create temp table _ad4_expected(rel text, owner text, used_by text) on commit drop;
  insert into _ad4_expected values
    {V};

  select count(*) into v_missing from _ad4_expected e
   where to_regclass('public.' || e.rel) is null
     and not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                      where n.nspname = 'public' and p.proname = e.rel);

  if v_missing = 0 then
    raise notice 'ad4_98: every relation the app reads EXISTS. Any red box left is NOT a missing view - open it and read the message, it carries the real Postgres error.';
  else
    select string_agg(distinct e.owner, ', ' order by e.owner) into v_files
      from _ad4_expected e
     where to_regclass('public.' || e.rel) is null
       and not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                        where n.nspname = 'public' and p.proname = e.rel);
    raise notice 'ad4_98: % relation(s) the app reads DO NOT EXIST. Run these files: %', v_missing, v_files;
    raise notice 'ad4_98: the table above lists every one, with the pages it makes red.';
  end if;

  raise notice '---- present but EMPTY (an empty box, not a red one) ----';
  for r in select e.rel from _ad4_expected e
            where to_regclass('public.' || e.rel) is not null
              and e.rel in ('markets','bands','book_snapshots','trades_observed','edges',
                            'band_probabilities','signals','paper_trades','live_weather',
                            'weather_observations','weather_forecasts','weather_events',
                            'fact_band_outcome','fact_forecast_outcome','fact_signal_outcome',
                            'derived_weather_peak','derived_forecast_skill')
            order by e.rel
  loop
    execute format('select count(*) from %I', r.rel) into v_empty;
    if v_empty = 0 then raise notice '  % has no rows yet', r.rel; end if;
  end loop;
end
$ad4$;
""".replace("{V}", values)
    return (HEALTH_HEAD % len(rows)) + body


if __name__ == "__main__":
    root = os.path.join(os.path.dirname(__file__), "..")
    owner = build()
    open(os.path.join(root, "web", "lib", "sqlOwner.ts"), "w").write(render(owner))
    open(os.path.join(root, "sql", "ad4_98_ui_health.sql"), "w").write(
        render_health(owner, pages_by_relation()))
    print(f"wrote {len(owner)} relations -> web/lib/sqlOwner.ts + sql/ad4_98_ui_health.sql")
