#!/usr/bin/env python3
"""Regenerate web/lib/sqlOwner.ts from sql/*.sql.

A missing-relation error should name the file that creates it. Hand-listing
that mapping guarantees it goes stale, so it is derived. Run this after adding
a SQL file; tests/test_web_display.py asserts it is current.
"""
import glob, json, os, re

def build() -> dict:
    owner = {}
    for f in sorted(glob.glob(os.path.join(os.path.dirname(__file__), "..", "sql", "*.sql"))):
        src = open(f).read()
        base = os.path.basename(f)
        for pat in (r"create\s+(?:or\s+replace\s+)?(?:materialized\s+)?view\s+(?:if\s+not\s+exists\s+)?([a-z0-9_]+)",
                    r"create\s+table\s+(?:if\s+not\s+exists\s+)?([a-z0-9_]+)"):
            for m in re.finditer(pat, src, re.I):
                owner.setdefault(m.group(1).lower(), base)
    return owner

def render(owner: dict) -> str:
    return ("// GENERATED by tools/gen_sql_owner.py - do not edit by hand.\n"
            "//\n"
            "// Which SQL file creates which relation. A missing-relation error used to say\n"
            '// "run sql/ad4_00_preflight.sql", which is right about one file in thirty and\n'
            "// wrong about the one you actually need: every Predictive panel failed on a\n"
            "// view created by ad4_31 and told the reader to run preflight.\n"
            "export const SQL_OWNER: Record<string, string> = "
            + json.dumps(owner, indent=2, sort_keys=True) + ";\n")

if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "..", "web", "lib", "sqlOwner.ts")
    open(out, "w").write(render(build()))
    print(f"wrote {len(build())} relations")
