#!/usr/bin/env python3
"""
Turn Natural Earth's 110m land polygons into a compact module the globe can
ship with, so the page has no runtime dependency on anything outside this repo.

    curl -sSLo /tmp/ne110.json \
      https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson
    python3 tools/gen_coastline.py /tmp/ne110.json web/lib/coastline.ts

WHY IT IS GENERATED AND NOT FETCHED. A globe that loads its own coastline over
the network is a globe that is a blank sphere whenever that host is slow, down,
or blocked - and this page is a trading surface. 130 KB of GeoJSON is too much
to inline as-is, so it is simplified to what the projection can actually
resolve and no further.

WHAT IS THROWN AWAY, on purpose:
  - Vertices closer together than the tolerance. At a 300 px radius one pixel
    is about 0.4 degrees at the equator; simplifying at 0.35 degrees keeps
    every coastline the projection can draw and drops the rest.
  - Rings whose bounding box is smaller than a couple of pixels. They render
    as a single dot and cost as much as a continent.
  - Everything after the first decimal place. 0.1 degrees is ~11 km, well
    under one pixel at this scale.

Natural Earth is public domain (CC0). Source and version are recorded in the
generated file's header.
"""
import json
import sys


def perpendicular_distance(pt, a, b):
    (x, y), (x1, y1), (x2, y2) = pt, a, b
    dx, dy = x2 - x1, y2 - y1
    if dx == 0 and dy == 0:
        return ((x - x1) ** 2 + (y - y1) ** 2) ** 0.5
    t = ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    px, py = x1 + t * dx, y1 + t * dy
    return ((x - px) ** 2 + (y - py) ** 2) ** 0.5


def simplify(points, tol):
    """Douglas-Peucker, iterative so a 1200-vertex ring cannot blow the stack."""
    if len(points) < 3:
        return points
    keep = [False] * len(points)
    keep[0] = keep[-1] = True
    stack = [(0, len(points) - 1)]
    while stack:
        i, j = stack.pop()
        if j <= i + 1:
            continue
        worst, worst_i = -1.0, -1
        for k in range(i + 1, j):
            d = perpendicular_distance(points[k], points[i], points[j])
            if d > worst:
                worst, worst_i = d, k
        if worst > tol:
            keep[worst_i] = True
            stack.append((i, worst_i))
            stack.append((worst_i, j))
    return [p for p, k in zip(points, keep) if k]


def rings_of(geom):
    t = geom["type"]
    if t == "Polygon":
        return [geom["coordinates"][0]]          # outer ring only
    if t == "MultiPolygon":
        return [poly[0] for poly in geom["coordinates"]]
    return []


def main(src, dst, tol=0.35, min_span=3.0):
    gj = json.load(open(src))
    out = []
    dropped = 0
    for feat in gj["features"]:
        for ring in rings_of(feat["geometry"]):
            pts = [(float(x), float(y)) for x, y in ring]
            xs = [p[0] for p in pts]
            ys = [p[1] for p in pts]
            if (max(xs) - min(xs)) < min_span and (max(ys) - min(ys)) < min_span:
                dropped += 1
                continue
            s = simplify(pts, tol)
            if len(s) < 4:
                dropped += 1
                continue
            out.append([[round(x, 1), round(y, 1)] for x, y in s])

    out.sort(key=len, reverse=True)
    n_pts = sum(len(r) for r in out)
    body = ",\n  ".join("[" + ",".join(f"[{x},{y}]" for x, y in r) + "]" for r in out)

    with open(dst, "w") as f:
        f.write(f'''/**
 * World coastlines, for the globe.
 *
 * GENERATED by tools/gen_coastline.py from Natural Earth 110m land
 * (ne_110m_land.geojson, public domain / CC0). Do not edit by hand - rerun
 * the generator.
 *
 * {len(out)} rings, {n_pts} points, simplified at {tol} degrees and quantised to
 * one decimal (~11 km). {dropped} ring(s) too small for this scale were
 * dropped: at a 300 px sphere they are a single pixel and cost as much to
 * carry as a continent.
 *
 * Each ring is [lon, lat] in degrees, outer boundary only - lakes and inland
 * seas are not cut out, because at this scale the hole would be smaller than
 * the line drawing it.
 */
export const LAND: Array<Array<[number, number]>> = [
  {body},
];
''')
    print(f"{len(out)} rings, {n_pts} points, {dropped} dropped -> {dst}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/tmp/ne110.json",
         sys.argv[2] if len(sys.argv) > 2 else "web/lib/coastline.ts")
