"""Per-city market weights (plan v2 P5.3, amended 28 Sep after P3.10 Q8): does
the rule in scripts/market_anchor.py give a city its own weight where the model
really knows more there, and keep it from cities where it does not?

Live evidence cannot answer that yet (on 28 Sep every scope had 1-4 settled
days), so this answers it on simulated ladders where the truth is known. Every
scenario, seed and size is fixed here, before any result was read.

The simulated world, one row per city-day (9 buckets):
  truth   a random ladder; the winner is drawn from it.
  market  0.6 truth + 0.4 noise.
  model   'informed': 0.9 truth + 0.1 noise (it knows what the price does not);
          'price+noise': 0.5 market + 0.5 noise (nothing beyond the price: its
          best weight is 0);
          'independent': 0.6 truth + 0.4 noise of its own (as good as the
          market, with errors of its own: a common weight above 0 helps
          every city alike, so no city should need its own).

Scenarios (48 cities, 60 settled days):
  A  every city price+noise       30 nights: the family should fail; no city moves.
  B  every city independent       30 nights: the scope earns its weight; no city its own.
  C  5 informed, 43 price+noise   10 nights: the 5 should move up; the 43 should not.

    python tools/p53_city_weights_sim.py > docs/CITY_WEIGHTS_SIMULATION_2026-09-28.md
"""
import os
import random
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "scripts"))
import market_anchor as ma          # noqa: E402

CITIES, DAYS, K = 48, 60, 9
SCOPE = "engine:morning"
INFORMED = {3, 11, 19, 27, 40}


def ladder(rng):
    v = [rng.random() ** 2 + 0.02 for _ in range(K)]
    s = sum(v)
    return [x / s for x in v]


def world(seed, kind_of):
    rng = random.Random(seed)
    rows = []
    for d in range(DAYS):
        date = f"2026-{10 + d // 28:02d}-{d % 28 + 1:02d}"
        for c in range(CITIES):
            bands = [f"b{i}" for i in range(K)]
            truth = ladder(rng)
            winner = rng.choices(bands, weights=truth)[0]
            market = [0.6 * t + 0.4 * b for t, b in zip(truth, ladder(rng))]
            noise = ladder(rng)
            kind = kind_of(c)
            if kind == "informed":
                model = [0.9 * t + 0.1 * b for t, b in zip(truth, noise)]
            elif kind == "independent":
                model = [0.6 * t + 0.4 * b for t, b in zip(truth, noise)]
            else:
                model = [0.5 * m + 0.5 * b for m, b in zip(market, noise)]
            rows.append((date, SCOPE, dict(zip(bands, model)), dict(zip(bands, market)), winner, f"c{c:02d}"))
    return rows


def run(seeds, kind_of, informed=()):
    out = {"nights": 0, "family_passed": 0, "scope_up": 0, "own_informed": 0, "own_other": 0, "gains": []}
    for seed in seeds:
        t = ma.fit(world(seed, kind_of), as_of="2026-12-31")
        ev = t["city_evidence"][SCOPE]
        own = t["city_weights"].get(SCOPE, {})
        out["nights"] += 1
        out["family_passed"] += ev["family"]["passed"]
        out["scope_up"] += t["weights"][SCOPE] > 0
        out["own_informed"] += sum(1 for c in own if int(c[1:]) in informed)
        out["own_other"] += sum(1 for c in own if int(c[1:]) not in informed)
        out["gains"].append((ev["family"]["gain"], ev["family"]["gain_lower90"]))
    return out


def main():
    p = print
    p("# Per-city market weights, on simulated ladders (28 Sep 2026)")
    p()
    p("Generated by `tools/p53_city_weights_sim.py`: the rule in `scripts/market_anchor.py` (CITIES), run on "
      "simulated worlds where it is known which cities the model knows more about. Scenarios, seeds and sizes "
      f"are fixed in the tool's docstring. {CITIES} cities, {DAYS} settled days, one row per city-day, "
      f"{K} buckets. One night = one fit from no previous table, so a city can take at most one step "
      f"({ma.MAX_STEP}).")
    p()
    p("| scenario | nights | family gate passed | scope's own weight above 0 | own weights, informed cities | "
      "own weights, other cities | family gain, median [its lower 90%] |")
    p("|---|---|---|---|---|---|---|")
    t0 = time.time()
    scen = [
        ("A: every city price+noise", range(30), lambda c: "price+noise", ()),
        ("B: every city independent", range(100, 130), lambda c: "independent", ()),
        ("C: 5 informed, 43 price+noise", range(200, 210),
         lambda c: "informed" if c in INFORMED else "price+noise", INFORMED),
    ]
    for name, seeds, kind_of, informed in scen:
        r = run(seeds, kind_of, informed)
        g = sorted(r["gains"])[len(r["gains"]) // 2]
        p(f"| {name} | {r['nights']} | {r['family_passed']} | {r['scope_up']} | "
          f"{r['own_informed']} of {r['nights'] * len(informed)} | "
          f"{r['own_other']} of {r['nights'] * (CITIES - len(informed))} | {g[0]:+.5f} [{g[1]:+.5f}] |")
    p()
    p(f"All three scenarios took {time.time() - t0:.0f} s on the machine that generated this file.")


if __name__ == "__main__":
    main()
