#!/usr/bin/env python3
"""How much of S10's view the market-anchored belief may take (plan v2 P5.3
amended), measured on the P7.3 replay's walk-forward ladders.

Input: the ladders scripts/backtest/replay_checkpoints.py writes with
--tops/--out-ladders - per checkpoint, S10's remaining-day ladder (its model
fitted only on days before the target's week) and the market ladder the
engine would have read at that moment (market_anchor.market_probs on the
newest top of book no older than 3 h, every band quoted).

Output: log loss on the venue's winner at every w of a 0.1 grid, per
checkpoint class; and market_anchor.fit itself, the nightly loop's fit,
walk-forward: refitted at each Monday from only the days before it, its
step taken from the previous refit. Nothing here is written anywhere; it
is the evidence for whether S10 has earned any weight.

    python tools/s10_market_weight.py LADDERS.jsonl.gz [--out-report PATH]
"""
import argparse
import datetime as dt
import gzip
import json
import math
import os
import sys
from collections import defaultdict

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "scripts"))

import market_anchor  # noqa: E402

GRID = [i / 10 for i in range(11)]


def load(path):
    with gzip.open(path, "rt") as f:
        return [json.loads(line) for line in f if line.strip()]


def usable(ladders):
    """[(date, scope, model, market, winner)] where the market is complete,
    both ladders cover the same bands, and the winner is on them."""
    out, dropped = [], defaultdict(int)
    for r in ladders:
        model, market, w = r["model"], r.get("market"), r["winner"]
        if market is None:
            dropped["no complete market ladder"] += 1
        elif set(model) != set(market):
            dropped["model and market ladders differ"] += 1
        elif w not in market:
            dropped["winner not on the ladder"] += 1
        else:
            out.append((r["target_date"], market_anchor.scope("s10", r["checkpoint"]), model, market, w))
    return out, dict(dropped)


def losses(rows):
    """{scope: {w: mean log loss}} and each scope's n rows and days."""
    by = defaultdict(list)
    for d, sc, m, k, w in rows:
        by[sc].append((d, m, k, w))
        by["all"].append((d, m, k, w))
    out = {}
    for sc, rs in sorted(by.items()):
        out[sc] = {"n": len(rs), "days": len({r[0] for r in rs}),
                   "ll": {w: sum(-math.log(market_anchor.anchor(m, k, w)[win]) for _d, m, k, win in rs) / len(rs)
                          for w in GRID}}
    return out


def walk_forward(rows):
    """market_anchor.fit at each Monday after the first date, previous = the last refit."""
    dates = sorted({r[0] for r in rows})
    first = dt.date.fromisoformat(dates[0])
    monday = first + dt.timedelta(days=(7 - first.weekday()) % 7 or 7)
    last = dt.date.fromisoformat(dates[-1]) + dt.timedelta(days=1)
    out, prev = [], None
    while monday <= last:
        t = market_anchor.fit(rows, monday, previous=prev)
        out.append(t)
        prev = t
        monday += dt.timedelta(days=7)
    final = market_anchor.fit(rows, last, previous=prev)
    out.append(final)
    return out


def report(ladders, rows, dropped, ll, fits):
    lines = ["# S10 against the market: how much weight has it earned? (P5.3 amended)", "",
             "Evidence from the P7.3 replay's walk-forward ladders (S10's remaining-day model fitted only on days "
             "before each target's week), each checkpoint's market read the engine's way "
             "(`market_anchor.market_probs` on the newest top of book no older than 3 h, every band quoted). "
             "Log loss on the venue's winner; lower is better. Generated by `tools/s10_market_weight.py`.", "",
             f"Checkpoints in the replay: {len(ladders)}; usable: {len(rows)}; left out: "
             + (", ".join(f"{k} {v}" for k, v in sorted(dropped.items())) or "none") + ".", "",
             "| scope | rows | days | " + " | ".join(f"w={w:.1f}" for w in GRID) + " | best w |",
             "|---|---|---|" + "---|" * len(GRID) + "---|"]
    for sc, v in ll.items():
        best = min(GRID, key=lambda w: (v["ll"][w], w))
        lines.append(f"| {sc} | {v['n']} | {v['days']} | " + " | ".join(f"{v['ll'][w]:.3f}" for w in GRID)
                     + f" | {best:.1f} |")
    lines += ["", "The nightly fit (`market_anchor.fit`: 20 settled days before a scope moves, a day-block "
              "bootstrap lower 90% bound on the gain above zero, at most 0.05 a refit), walk-forward, refitted "
              "each Monday from the days before it:", "",
              "| as of | scope | days | rows | best w | gain per row | lower 90% | weight |", "|---|---|---|---|---|---|---|---|"]
    for t in fits:
        for sc, e in sorted(t["evidence"].items()):
            lines.append(f"| {t['as_of']} | {sc} | {e.get('days')} | {e.get('rows', '')} | {e.get('best_w', '')} | "
                         f"{e.get('gain', '')} | {e.get('gain_lower90', '')} | {t['weights'].get(sc)} |")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("ladders")
    ap.add_argument("--out-report")
    a = ap.parse_args(argv)
    ladders = load(a.ladders)
    rows, dropped = usable(ladders)
    ll = losses(rows)
    fits = walk_forward(rows) if rows else []
    text = report(ladders, rows, dropped, ll, fits)
    if a.out_report:
        open(a.out_report, "w").write(text)
    print(text)
    return ll, fits


if __name__ == "__main__":
    main()
