-- ===========================================================================
-- ad4_98_ui_health.sql - WHY IS THE UI SHOWING RED BOXES?
--
-- GENERATED by tools/gen_sql_owner.py from the app's own source. Do not edit.
--
-- READ-ONLY. It creates nothing and changes nothing. Run it any time.
--
-- A RED box on an AD4 page is one thing: a query that failed, almost always
-- because the view behind it does not exist yet. This checks every relation
-- and function the app reads - 112 of them - and for each MISSING one names the
-- SQL file that creates it and the pages that go red without it.
--
-- An EMPTY box (dashed border, grey text, naming a job to run) is NOT a fault
-- and NOT a red box: the view exists and has no rows yet because the job that
-- fills it has not run. Those are listed separately at the end.
-- ===========================================================================

with expected(rel, owner, used_by) as (values
    ('anomalies', 'ad4_00_preflight.sql', ''),
    ('anomaly_rules', 'ad4_phase2.sql', ''),
    ('backtest_results', 'ad4_00_preflight.sql', '/backtest'),
    ('backtest_runs', 'ad4_00_preflight.sql', '/backtest'),
    ('backtest_trades', 'ad4_00_preflight.sql', ''),
    ('band_probabilities', 'ad4_00_preflight.sql', '/analytics'),
    ('bands', 'ad4_00_preflight.sql', '(SignalsPanel)'),
    ('book_snapshots', 'ad4_00_preflight.sql', ''),
    ('cities', 'ad4_00_preflight.sql', '(Header), (RightRail), (ScopeControl), /, /campaigns, /live, /predictive'),
    ('cost_params', 'ad4_phase2.sql', ''),
    ('data_freshness_spec', 'ad4_39_freshness.sql', ''),
    ('deployments', 'ad4_00_preflight.sql', ''),
    ('derived_band_day_volume', 'ad4_00_preflight.sql', ''),
    ('derived_calibration_adjustment', 'ad4_45_calibration_feedback.sql', ''),
    ('derived_capacity', 'ad4_phase2.sql', ''),
    ('derived_city_climate', 'ad4_19_stats_cache.sql', ''),
    ('derived_city_correlation', 'ad4_phase2.sql', ''),
    ('derived_city_day_features', 'ad4_00_preflight.sql', ''),
    ('derived_city_day_volume', 'ad4_00_preflight.sql', ''),
    ('derived_climb_profile', 'ad4_28_feature_cache.sql', ''),
    ('derived_forecast_skill', 'ad4_00_preflight.sql', '/analytics'),
    ('derived_market_peak', 'ad4_00_preflight.sql', ''),
    ('derived_model_forecast', 'ad4_25_model_forecast.sql', ''),
    ('derived_weather_model', 'ad4_21_weather_features.sql', ''),
    ('derived_weather_peak', 'ad4_00_preflight.sql', '/live'),
    ('edges', 'ad4_phase2.sql', ''),
    ('fact_band_outcome', 'ad4_18_databank.sql', '(ModelAnalytics)'),
    ('fact_forecast_outcome', 'ad4_18_databank.sql', ''),
    ('fact_signal_outcome', 'ad4_18_databank.sql', ''),
    ('ingest_log', 'ad4_00_preflight.sql', '(PipelineStatus)'),
    ('ledger', 'ad4_00_preflight.sql', ''),
    ('live_weather', 'ad4_live_weather.sql', '(GlobalBar), (RightRail), /board, /live, /opportunities'),
    ('markets', 'ad4_00_preflight.sql', '(Header)'),
    ('model_versions', 'ad4_00_preflight.sql', ''),
    ('paper_trades', 'ad4_00_preflight.sql', '(GlobalBar), /, /analytics, /goals'),
    ('settings', 'ad4_00_preflight.sql', '(GlobalBar), (ScheduleControl), /goals, /workflows'),
    ('signals', 'ad4_00_preflight.sql', '(SignalsPanel), /, /analytics'),
    ('strategies', 'ad4_00_preflight.sql', '(SignalsPanel), /campaigns'),
    ('strategy_conflicts', 'ad4_phase2.sql', ''),
    ('synthesis_thresholds', 'ad4_40_synthesis.sql', ''),
    ('trades_observed', 'ad4_00_preflight.sql', ''),
    ('v_archive_by_city', 'ad4_35_databank_inventory.sql', '/databank'),
    ('v_archive_daily', 'ad4_35_databank_inventory.sql', '/databank'),
    ('v_archive_inventory', 'ad4_35_databank_inventory.sql', '/databank'),
    ('v_backtest_window', 'ad4_42_backtest.sql', '/backtest'),
    ('v_band_book', 'ad4_13_reconcile.sql', ''),
    ('v_band_ladder', 'ad4_34_trade_plan.sql', ''),
    ('v_band_price_history', 'ad4_26_temp_trend.sql', '/monitor'),
    ('v_band_volume', 'ad4_13_reconcile.sql', ''),
    ('v_bankroll_curve', 'ad4_31_predictive.sql', '/predictive'),
    ('v_book_ladder', 'ad4_13_reconcile.sql', ''),
    ('v_calibration', 'ad4_18_databank.sql', '(DataBank), (ModelAnalytics)'),
    ('v_campaign_state', 'ad4_41_campaigns.sql', '/campaigns'),
    ('v_campaign_targets', 'ad4_41_campaigns.sql', ''),
    ('v_city_climate', 'ad4_17_city_stats.sql', ''),
    ('v_city_climb_profile', 'ad4_26_temp_trend.sql', '(ModelAnalytics)'),
    ('v_city_climb_profile_live', 'ad4_26_temp_trend.sql', ''),
    ('v_city_daily_max', 'ad4_17_city_stats.sql', ''),
    ('v_city_day_features', 'ad4_21_weather_features.sql', ''),
    ('v_city_day_plan', 'ad4_34_trade_plan.sql', '/opportunities'),
    ('v_city_peak_approach', 'ad4_26_temp_trend.sql', '(RightRail), /live, /monitor'),
    ('v_city_reasoning', 'ad4_23_reasoning.sql', '(Reasoning)'),
    ('v_city_stats', 'ad4_17_city_stats.sql', ''),
    ('v_city_temp_trend', 'ad4_26_temp_trend.sql', ''),
    ('v_city_today_readings', 'ad4_26_temp_trend.sql', '/monitor'),
    ('v_city_volume', 'ad4_13_reconcile.sql', '(GlobalBar), /, /live'),
    ('v_condition_skill', 'ad4_24_nws_gridpoint.sql', '(ModelAnalytics)'),
    ('v_data_freshness', 'ad4_39_freshness.sql', ''),
    ('v_data_health', 'ad4_39_freshness.sql', ''),
    ('v_databank_coverage', 'ad4_18_databank.sql', '(DataBank)'),
    ('v_edge_realisation', 'ad4_18_databank.sql', '(DataBank), (ModelAnalytics)'),
    ('v_edge_scaling', 'ad4_31_predictive.sql', '/predictive'),
    ('v_execution_budget', 'ad4_20_schedules.sql', '(ScheduleControl)'),
    ('v_execution_limits', 'ad4_36_execution_limits.sql', ''),
    ('v_forecast_audit', 'ad4_43_forecast_audit.sql', ''),
    ('v_forecast_candidates', 'ad4_43_forecast_audit.sql', ''),
    ('v_forecast_convergence', 'ad4_31_predictive.sql', '/predictive'),
    ('v_forecast_coverage', 'ad4_30_open_meteo.sql', ''),
    ('v_forecast_divergence', 'ad4_16_nws.sql', ''),
    ('v_forecast_divergence_current', 'ad4_19_stats_cache.sql', ''),
    ('v_forecast_features', 'ad4_24_nws_gridpoint.sql', ''),
    ('v_latest_book', 'ad4_13_reconcile.sql', '/board, /goals, /opportunities'),
    ('v_latest_edge', 'ad4_phase2.sql', ''),
    ('v_latest_prob', 'ad4_phase2.sql', ''),
    ('v_learning_state', 'ad4_40_synthesis.sql', '/synthesis'),
    ('v_model_disagreement', 'ad4_25_model_forecast.sql', '(Reasoning)'),
    ('v_model_forecast_current', 'ad4_25_model_forecast.sql', ''),
    ('v_model_forecast_skill', 'ad4_25_model_forecast.sql', '(ModelAnalytics)'),
    ('v_opportunities', 'ad4_13_reconcile.sql', '(CityWatch), (Header), (ModelAnalytics), (SignalsPanel), /, /analytics, /board, /goals, /live, /monitor'),
    ('v_opportunity_context', 'ad4_22_opportunity_context.sql', '/opportunities'),
    ('v_peak_hour_coverage', 'ad4_37_peak_hour.sql', '/globe'),
    ('v_persistence_skill', 'ad4_21_weather_features.sql', '(ModelAnalytics)'),
    ('v_prediction_ladder', 'ad4_31_predictive.sql', '/predictive'),
    ('v_prediction_scorecard', 'ad4_31_predictive.sql', '/predictive'),
    ('v_provisional_settings', 'ad4_39_freshness.sql', '(Provenance)'),
    ('v_run_scope', 'ad4_32_run_scope.sql', '(ScopeControl)'),
    ('v_sigma_inputs', 'ad4_45_calibration_feedback.sql', ''),
    ('v_storage_report', 'ad4_29_retention.sql', ''),
    ('v_strategy_board', 'ad4_33_control.sql', '/analytics, /strategies'),
    ('v_strategy_params', 'ad4_34_trade_plan.sql', ''),
    ('v_synthesis_findings', 'ad4_40_synthesis.sql', '/synthesis'),
    ('v_synthesis_inventory', 'ad4_35_databank_inventory.sql', '/databank'),
    ('v_table_scan_risk', 'ad4_44_indexes.sql', ''),
    ('v_trade_plan', 'ad4_34_trade_plan.sql', '/goals, /opportunities, /strategies'),
    ('v_trade_timing', 'ad4_33_control.sql', '/goals'),
    ('v_weather_effects', 'ad4_21_weather_features.sql', '(ModelAnalytics)'),
    ('v_workflow_runs', 'ad4_14_workflows.sql', '/workflows'),
    ('v_write_access', 'ad4_38_grants.sql', ''),
    ('weather_events', 'ad4_live_weather.sql', '(RightRail), /live'),
    ('weather_forecast_features', 'ad4_24_nws_gridpoint.sql', ''),
    ('weather_forecasts', 'ad4_00_preflight.sql', '/board, /live'),
    ('weather_observations', 'ad4_00_preflight.sql', '/live')
),
checked as (
  select e.*,
         (to_regclass('public.' || e.rel) is not null) as is_relation,
         exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                  where n.nspname = 'public' and p.proname = e.rel) as is_function
    from expected e
)
select
  rel                     as missing_relation,
  owner                   as run_this_file,
  nullif(used_by, '')     as pages_that_go_red
from checked
where not (is_relation or is_function)
order by owner, rel;


do $ad4$
declare v_missing int; v_files text; v_empty int; r record;
begin
  create temp table _ad4_expected(rel text, owner text, used_by text) on commit drop;
  insert into _ad4_expected values
    ('anomalies', 'ad4_00_preflight.sql', ''),
    ('anomaly_rules', 'ad4_phase2.sql', ''),
    ('backtest_results', 'ad4_00_preflight.sql', '/backtest'),
    ('backtest_runs', 'ad4_00_preflight.sql', '/backtest'),
    ('backtest_trades', 'ad4_00_preflight.sql', ''),
    ('band_probabilities', 'ad4_00_preflight.sql', '/analytics'),
    ('bands', 'ad4_00_preflight.sql', '(SignalsPanel)'),
    ('book_snapshots', 'ad4_00_preflight.sql', ''),
    ('cities', 'ad4_00_preflight.sql', '(Header), (RightRail), (ScopeControl), /, /campaigns, /live, /predictive'),
    ('cost_params', 'ad4_phase2.sql', ''),
    ('data_freshness_spec', 'ad4_39_freshness.sql', ''),
    ('deployments', 'ad4_00_preflight.sql', ''),
    ('derived_band_day_volume', 'ad4_00_preflight.sql', ''),
    ('derived_calibration_adjustment', 'ad4_45_calibration_feedback.sql', ''),
    ('derived_capacity', 'ad4_phase2.sql', ''),
    ('derived_city_climate', 'ad4_19_stats_cache.sql', ''),
    ('derived_city_correlation', 'ad4_phase2.sql', ''),
    ('derived_city_day_features', 'ad4_00_preflight.sql', ''),
    ('derived_city_day_volume', 'ad4_00_preflight.sql', ''),
    ('derived_climb_profile', 'ad4_28_feature_cache.sql', ''),
    ('derived_forecast_skill', 'ad4_00_preflight.sql', '/analytics'),
    ('derived_market_peak', 'ad4_00_preflight.sql', ''),
    ('derived_model_forecast', 'ad4_25_model_forecast.sql', ''),
    ('derived_weather_model', 'ad4_21_weather_features.sql', ''),
    ('derived_weather_peak', 'ad4_00_preflight.sql', '/live'),
    ('edges', 'ad4_phase2.sql', ''),
    ('fact_band_outcome', 'ad4_18_databank.sql', '(ModelAnalytics)'),
    ('fact_forecast_outcome', 'ad4_18_databank.sql', ''),
    ('fact_signal_outcome', 'ad4_18_databank.sql', ''),
    ('ingest_log', 'ad4_00_preflight.sql', '(PipelineStatus)'),
    ('ledger', 'ad4_00_preflight.sql', ''),
    ('live_weather', 'ad4_live_weather.sql', '(GlobalBar), (RightRail), /board, /live, /opportunities'),
    ('markets', 'ad4_00_preflight.sql', '(Header)'),
    ('model_versions', 'ad4_00_preflight.sql', ''),
    ('paper_trades', 'ad4_00_preflight.sql', '(GlobalBar), /, /analytics, /goals'),
    ('settings', 'ad4_00_preflight.sql', '(GlobalBar), (ScheduleControl), /goals, /workflows'),
    ('signals', 'ad4_00_preflight.sql', '(SignalsPanel), /, /analytics'),
    ('strategies', 'ad4_00_preflight.sql', '(SignalsPanel), /campaigns'),
    ('strategy_conflicts', 'ad4_phase2.sql', ''),
    ('synthesis_thresholds', 'ad4_40_synthesis.sql', ''),
    ('trades_observed', 'ad4_00_preflight.sql', ''),
    ('v_archive_by_city', 'ad4_35_databank_inventory.sql', '/databank'),
    ('v_archive_daily', 'ad4_35_databank_inventory.sql', '/databank'),
    ('v_archive_inventory', 'ad4_35_databank_inventory.sql', '/databank'),
    ('v_backtest_window', 'ad4_42_backtest.sql', '/backtest'),
    ('v_band_book', 'ad4_13_reconcile.sql', ''),
    ('v_band_ladder', 'ad4_34_trade_plan.sql', ''),
    ('v_band_price_history', 'ad4_26_temp_trend.sql', '/monitor'),
    ('v_band_volume', 'ad4_13_reconcile.sql', ''),
    ('v_bankroll_curve', 'ad4_31_predictive.sql', '/predictive'),
    ('v_book_ladder', 'ad4_13_reconcile.sql', ''),
    ('v_calibration', 'ad4_18_databank.sql', '(DataBank), (ModelAnalytics)'),
    ('v_campaign_state', 'ad4_41_campaigns.sql', '/campaigns'),
    ('v_campaign_targets', 'ad4_41_campaigns.sql', ''),
    ('v_city_climate', 'ad4_17_city_stats.sql', ''),
    ('v_city_climb_profile', 'ad4_26_temp_trend.sql', '(ModelAnalytics)'),
    ('v_city_climb_profile_live', 'ad4_26_temp_trend.sql', ''),
    ('v_city_daily_max', 'ad4_17_city_stats.sql', ''),
    ('v_city_day_features', 'ad4_21_weather_features.sql', ''),
    ('v_city_day_plan', 'ad4_34_trade_plan.sql', '/opportunities'),
    ('v_city_peak_approach', 'ad4_26_temp_trend.sql', '(RightRail), /live, /monitor'),
    ('v_city_reasoning', 'ad4_23_reasoning.sql', '(Reasoning)'),
    ('v_city_stats', 'ad4_17_city_stats.sql', ''),
    ('v_city_temp_trend', 'ad4_26_temp_trend.sql', ''),
    ('v_city_today_readings', 'ad4_26_temp_trend.sql', '/monitor'),
    ('v_city_volume', 'ad4_13_reconcile.sql', '(GlobalBar), /, /live'),
    ('v_condition_skill', 'ad4_24_nws_gridpoint.sql', '(ModelAnalytics)'),
    ('v_data_freshness', 'ad4_39_freshness.sql', ''),
    ('v_data_health', 'ad4_39_freshness.sql', ''),
    ('v_databank_coverage', 'ad4_18_databank.sql', '(DataBank)'),
    ('v_edge_realisation', 'ad4_18_databank.sql', '(DataBank), (ModelAnalytics)'),
    ('v_edge_scaling', 'ad4_31_predictive.sql', '/predictive'),
    ('v_execution_budget', 'ad4_20_schedules.sql', '(ScheduleControl)'),
    ('v_execution_limits', 'ad4_36_execution_limits.sql', ''),
    ('v_forecast_audit', 'ad4_43_forecast_audit.sql', ''),
    ('v_forecast_candidates', 'ad4_43_forecast_audit.sql', ''),
    ('v_forecast_convergence', 'ad4_31_predictive.sql', '/predictive'),
    ('v_forecast_coverage', 'ad4_30_open_meteo.sql', ''),
    ('v_forecast_divergence', 'ad4_16_nws.sql', ''),
    ('v_forecast_divergence_current', 'ad4_19_stats_cache.sql', ''),
    ('v_forecast_features', 'ad4_24_nws_gridpoint.sql', ''),
    ('v_latest_book', 'ad4_13_reconcile.sql', '/board, /goals, /opportunities'),
    ('v_latest_edge', 'ad4_phase2.sql', ''),
    ('v_latest_prob', 'ad4_phase2.sql', ''),
    ('v_learning_state', 'ad4_40_synthesis.sql', '/synthesis'),
    ('v_model_disagreement', 'ad4_25_model_forecast.sql', '(Reasoning)'),
    ('v_model_forecast_current', 'ad4_25_model_forecast.sql', ''),
    ('v_model_forecast_skill', 'ad4_25_model_forecast.sql', '(ModelAnalytics)'),
    ('v_opportunities', 'ad4_13_reconcile.sql', '(CityWatch), (Header), (ModelAnalytics), (SignalsPanel), /, /analytics, /board, /goals, /live, /monitor'),
    ('v_opportunity_context', 'ad4_22_opportunity_context.sql', '/opportunities'),
    ('v_peak_hour_coverage', 'ad4_37_peak_hour.sql', '/globe'),
    ('v_persistence_skill', 'ad4_21_weather_features.sql', '(ModelAnalytics)'),
    ('v_prediction_ladder', 'ad4_31_predictive.sql', '/predictive'),
    ('v_prediction_scorecard', 'ad4_31_predictive.sql', '/predictive'),
    ('v_provisional_settings', 'ad4_39_freshness.sql', '(Provenance)'),
    ('v_run_scope', 'ad4_32_run_scope.sql', '(ScopeControl)'),
    ('v_sigma_inputs', 'ad4_45_calibration_feedback.sql', ''),
    ('v_storage_report', 'ad4_29_retention.sql', ''),
    ('v_strategy_board', 'ad4_33_control.sql', '/analytics, /strategies'),
    ('v_strategy_params', 'ad4_34_trade_plan.sql', ''),
    ('v_synthesis_findings', 'ad4_40_synthesis.sql', '/synthesis'),
    ('v_synthesis_inventory', 'ad4_35_databank_inventory.sql', '/databank'),
    ('v_table_scan_risk', 'ad4_44_indexes.sql', ''),
    ('v_trade_plan', 'ad4_34_trade_plan.sql', '/goals, /opportunities, /strategies'),
    ('v_trade_timing', 'ad4_33_control.sql', '/goals'),
    ('v_weather_effects', 'ad4_21_weather_features.sql', '(ModelAnalytics)'),
    ('v_workflow_runs', 'ad4_14_workflows.sql', '/workflows'),
    ('v_write_access', 'ad4_38_grants.sql', ''),
    ('weather_events', 'ad4_live_weather.sql', '(RightRail), /live'),
    ('weather_forecast_features', 'ad4_24_nws_gridpoint.sql', ''),
    ('weather_forecasts', 'ad4_00_preflight.sql', '/board, /live'),
    ('weather_observations', 'ad4_00_preflight.sql', '/live');

  select count(*) into v_missing from _ad4_expected e
   where to_regclass('public.' || e.rel) is null
     and not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                      where n.nspname = 'public' and p.proname = e.rel);

  if v_missing = 0 then
    raise notice 'ad4_98: every relation the app reads EXISTS. Any red box left is NOT a missing view - open it and read the message, it carries the real Postgres error.';
  else
    select string_agg(distinct e.owner, ', ' order by e.owner) into v_files
      from _ad4_expected e
     where to_regclass('public.' || e.rel) is null
       and not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                        where n.nspname = 'public' and p.proname = e.rel);
    raise notice 'ad4_98: % relation(s) the app reads DO NOT EXIST. Run these files: %', v_missing, v_files;
    raise notice 'ad4_98: the table above lists every one, with the pages it makes red.';
  end if;

  raise notice '---- present but EMPTY (an empty box, not a red one) ----';
  for r in select e.rel from _ad4_expected e
            where to_regclass('public.' || e.rel) is not null
              and e.rel in ('markets','bands','book_snapshots','trades_observed','edges',
                            'band_probabilities','signals','paper_trades','live_weather',
                            'weather_observations','weather_forecasts','weather_events',
                            'fact_band_outcome','fact_forecast_outcome','fact_signal_outcome',
                            'derived_weather_peak','derived_forecast_skill')
            order by e.rel
  loop
    execute format('select count(*) from %I', r.rel) into v_empty;
    if v_empty = 0 then raise notice '  % has no rows yet', r.rel; end if;
  end loop;
end
$ad4$;
